### ISSUE TITLE
Support `background_by` and `background_ref` properties

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/petridish#55]
These properties would show the source of an image in the bottom right

<img width="1028" alt="Screenshot 2022-10-18 at 10 41 16" src="https://user-images.githubusercontent.com/600993/196367442-87d8b1c0-b9a4-4a4d-b20f-ef580368b868.png">

**Comment by peterdesmet** [comment]
This would also support the `background_alt` use case in https://github.com/echinopscis/echinopscis.github.io/blob/bd75a37c92482c4c9df96d858fee3aabe53b3380/_posts/2022-08-02-tdwg2022.md

**Comment by peterdesmet** [comment]
Alternatively, group those properties:

```yml
---
title: Markdown
description: >
  You write your content in [Markdown](https://guides.github.com/features/mastering-markdown/).
  This page shows how it is rendered by Petridish.
background:
  img: https://images.unsplash.com/photo-1550089479-fe0e48e7d788?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjR8fGJpcmR8ZW58MHwwfDB8fA%3D%3D&auto=format&fit=crop&w=1200&h=600&q=80
  by: Krzysztof Niewolny
  href: https://unsplash.com/photos/pTfcnk9WZHA
toc: true
order: 3
---
```
