### ISSUE TITLE
Add layout for slides

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/petridish#72]
See https://echinopscis.github.io/blog/2022/tdwg-conference-lightning-talk/ by @nickynicolson in which slide information is added to [front matter](https://github.com/echinopscis/echinopscis.github.io/blob/main/_posts/2022-10-18-tdwg-conference-lightning-talk.md?plain=1#L9):

```yaml
slides:
  - img: /assets/images/tdwg2022-ltd14/Slide1.PNG
    img_alt: "Open science tools: Supporting hands-on creation of the “digital extended specimen”"
    notes: |
      Work is a collaboration between [Nicky Nicolson](https://www.kew.org/science/our-science/people/nicky-nicolson) (NN) and [Eve Lucas](https://www.kew.org/science/our-science/people/eve-lucas) (EL) both from [Kew Science](https://www.kew.org/science)
  - img: /assets/images/tdwg2022-ltd14/Slide2.PNG
    img_alt: "Explain personal and institutional contexts"
    notes: |
      Personal context: **NN** transitioned from software development into research, and is interested in how software development practices can be used in research. Institutionally, we have a commitment to accelerate taxonomy using digital practices, and we started a collaborative project to explore this, using institutional knowledge from the e-taxonomic approaches, but exploring what technical advances could be used in e-taxonomy today. 
    video_offset: 0m31s
```

The [slides](https://github.com/echinopscis/echinopscis.github.io/blob/main/_layouts/slides.html) layout then renders on the page as (including option to jump to video)

<img width="1128" alt="Screenshot 2022-12-14 at 08 40 47" src="https://user-images.githubusercontent.com/600993/207535061-97e89b9b-4239-41ac-b394-51ac19b9dd73.png">

Observations:

- Is it better to have this info in front matter or as a _data/file.yml ? Since it is for a single page, it might be good to keep it together, but doesn't follow conventions.
- Would change layout so that text appears under (rather than next to slide) on small screens.
