### ISSUE TITLE
Add print.css

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/petridish#95]
As reported by https://github.com/tdwg/website/issues/524, more could be done to make Petridish websites print friendly. There are two main approaches:

1. Add a `assets/css/print.css` (or scss) and call it in head with:

```html
<link rel="stylesheet" media="print" href="{{ '/assets/theme/css/print.css' | relative_url }}">
```

Use https://tdwg.github.io/ltc/static/custom/css/print.css as inspiration. The advantage is that all print related elements are together. The disadvantage is that when updating a certain element (like the `navbar`), it is easy to forget the print related changes too.

2. Add `@media print` [rules](https://www.sitepoint.com/css-printer-friendly-pages/) in context:

```css
/* override styles when printing */
@media print {

  body {
    margin: 0;
    color: #000;
    background-color: #fff;
  }
}
```

The advantage is that all css is kept in context.

I think I prefer the latter approach. If done so, than https://github.com/peterdesmet/petridish/commit/efb9a64438086376f9f36dd8df6cd93caefa9aa9 could be updated to make use of `@media` elements.
